apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wallet-stack
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/container-dependencies: |
          {"wallet-frontend":["wallet-backend"], "wallet-backend":["pid-db"], "pid-provider":["pid-db"], "trusted-list":["pid-db"], "relying-party":["trusted-list"], "reverse-proxy":["relying-party", "trusted-list", "pid-provider", "wallet-backend", "wallet-frontend"]}
    spec:
      containers:
        - name: reverse-proxy
          image: cpu64/reverse-proxy:latest
          command: ["/cloud-run-entrypoint.sh"]
          ports:
            - containerPort: 8080
        - name: relying-party
          image: cpu64/relying-party:latest
          env:
            - name: SERVICE_NAME
              value: "The relying party service"
            - name: PORT
              value: "8001"
        - name: trusted-list
          image: cpu64/trusted-list:latest
          command: ["sh", "-c", "update-ca-certificates && hypercorn app:app --bind 127.0.0.1:8002"]
          env:
            - name: SERVICE_NAME
              value: "List of trusted providers service"
        - name: pid-provider
          image: cpu64/pid-provider:latest
          command: ["sh", "-c", "update-ca-certificates && hypercorn app:app --bind 127.0.0.1:8003"]
          env:
            - name: SERVICE_NAME
              value: "PID provider service"
            - name: PGHOST
              value: "127.0.0.1"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              value: "password"
            - name: PGDATABASE
              value: "piddb"
            - name: PGPORT
              value: "5432"
            - name: SECRET_KEY
              value: "Paslaptingasis_Raktas!!"
        - name: wallet-backend
          image: cpu64/wallet-backend:latest
          command: ["sh", "-c", "uv run python -m hypercorn app.app:app --bind 127.0.0.1:8004"]
          env:
            - name: SERVICE_NAME
              value: "Backend service"
        - name: wallet-frontend
          image: cpu64/wallet-frontend:latest
          env:
            - name: SERVICE_NAME
              value: "Frontend service"
          command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/cloud-run-nginx.conf"]
        - name: pid-db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "piddb"
