services:
  relying-party:
    build: ./relying-party
    image: cpu64/relying-party:latest
    container_name: relying-party
    environment:
      SERVICE_NAME: "The relying party service"
    expose:
      - "8000"
    networks:
      - wallet-net
    volumes:
      - ./certs/root-ca.crt:/usr/local/share/ca-certificates/root-ca.crt:ro

  trusted-list:
    build: ./trusted-list
    image: cpu64/trusted-list:latest
    container_name: trusted-list
    environment:
      SERVICE_NAME: "List of trusted providers service"
    expose:
      - "8000"
    networks:
      - wallet-net
    volumes:
      - ./certs/root-ca.crt:/usr/local/share/ca-certificates/root-ca.crt:ro

  pid-provider:
    build: ./pid-provider
    image: cpu64/pid-provider:latest
    container_name: pid-provider
    depends_on:
      pid-db:
        condition: service_healthy
    environment:
      SERVICE_NAME: "PID provider service"
      PGHOST: pid-db
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: piddb
      PGPORT: "5432"
      TZ: Europe/Vilnius
      SECRET_KEY: Paslaptingasis_Raktas!!
    expose:
      - "8000"
    networks:
      - wallet-net
    volumes:
      - ./certs/root-ca.crt:/usr/local/share/ca-certificates/root-ca.crt:ro
      - ./pid-provider/app/keys:/app/keys

  pid-db:
    image: postgres:18-alpine
    container_name: pid-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: piddb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d piddb"]
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - wallet-net
    volumes:
      - ./pid-provider/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  wallet-backend:
    build: ./wallet-backend
    image: cpu64/wallet-backend:latest
    container_name: wallet-backend
    environment:
      SERVICE_NAME: "Backend service"
    expose:
      - "8000"
    networks:
      - wallet-net
    volumes:
      - ./certs/root-ca.crt:/usr/local/share/ca-certificates/root-ca.crt:ro
    command: sh -c "uv run python -m hypercorn app.app:app --bind 0.0.0.0:8000"

  wallet-frontend:
    build: ./wallet-frontend
    image: cpu64/wallet-frontend:latest
    container_name: wallet-frontend
    environment:
      SERVICE_NAME: "Frontend service"
    expose:
      - "8000"
    networks:
      - wallet-net

  reverse-proxy:
    build: ./reverse-proxy
    image: cpu64/reverse-proxy:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
       - relying-party
       - trusted-list
       - pid-provider
       - wallet-backend
       - wallet-frontend
    networks:
      wallet-net:
        aliases:
          - relying-party.wallet.test
          - public.relying-party.wallet.test
          - trusted-list.wallet.test
          - public.trusted-list.wallet.test
          - pid-provider.wallet.test
          - public.pid-provider.wallet.test
          - wallet-backend.wallet.test
          - public.wallet-backend.wallet.test
          - wallet-frontend.wallet.test
          - public.wallet-frontend.wallet.test
    volumes:
      - ./certs/wildcard.test.crt:/etc/nginx/certs/wildcard.test.crt:ro
      - ./certs/wildcard.test.key:/etc/nginx/certs/wildcard.test.key:ro

networks:
  wallet-net:
