name: Build and lint services

on: [push]

jobs:
  build-docker-images:
    name: Build all docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build prod images
        run: cd src && docker compose -f docker-compose.yml build

      - name: Build dev images
        run: cd src && docker compose -f docker-compose.yml -f docker-compose.dev.yml build
